"""Initial migration

Revision ID: 36dd20121b50
Revises: 
Create Date: 2025-05-09 21:08:08.261830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dd20121b50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_evento')
    
    # Crear una tabla temporal para repuestos
    op.create_table('repuesto_temp',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('codigo', sa.String(length=50), nullable=False),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('stock', sa.Integer(), nullable=True),
        sa.Column('stock_minimo', sa.Integer(), nullable=True),
        sa.Column('precio', sa.Float(), nullable=False),
        sa.Column('categoria', sa.String(length=50), nullable=True),
        sa.Column('estado', sa.String(length=20), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codigo', name='uq_repuesto_codigo')
    )
    
    # Copiar datos de la tabla original a la temporal
    op.execute("""
        INSERT INTO repuesto_temp (
            id, nombre, codigo, descripcion, stock, stock_minimo, precio,
            categoria, estado, fecha_creacion, fecha_actualizacion
        )
        SELECT 
            id, nombre, 'REP-' || id, descripcion, stock, stock_minimo, 0,
            NULL, 'activo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM repuesto
    """)
    
    # Eliminar la tabla original
    op.drop_table('repuesto')
    
    # Renombrar la tabla temporal
    op.rename_table('repuesto_temp', 'repuesto')

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recordatorio', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recordatorio_enviado', sa.Boolean(), nullable=True))
        batch_op.alter_column('mecanico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('notas')

    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.alter_column('vehiculo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('servicio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('impuestos',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('mecanico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
        batch_op.drop_column('tarifa_hora')
        batch_op.drop_column('activo')
        batch_op.drop_column('horas_trabajo')

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.alter_column('mecanico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tipo_servicio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('servicio_repuesto', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('kilometraje',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('kilometraje',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('servicio_repuesto', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.alter_column('tipo_servicio',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mecanico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('total')

    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.drop_constraint('uq_repuesto_codigo', type_='unique')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('estado')
        batch_op.drop_column('categoria')
        batch_op.drop_column('precio')
        batch_op.drop_column('codigo')

    with op.batch_alter_table('mecanico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas_trabajo', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('tarifa_hora', sa.FLOAT(), nullable=True))
        batch_op.drop_column('estado')

    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.alter_column('impuestos',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('servicio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vehiculo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.TEXT(), nullable=True))
        batch_op.alter_column('mecanico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('recordatorio_enviado')
        batch_op.drop_column('recordatorio')
        batch_op.drop_column('tipo')

    op.create_table('_alembic_tmp_evento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('recordatorio', sa.BOOLEAN(), nullable=True),
    sa.Column('recordatorio_enviado', sa.BOOLEAN(), nullable=True),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('fecha_inicio', sa.DATETIME(), nullable=False),
    sa.Column('fecha_fin', sa.DATETIME(), nullable=False),
    sa.Column('mecanico_id', sa.INTEGER(), nullable=True),
    sa.Column('servicio_id', sa.INTEGER(), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanico.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
