"""Actualizar modelo Evento con nuevos campos

Revision ID: 78c524f3b82d
Revises: a06d8a8ba2c4
Create Date: 2025-05-19 18:38:29.100060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c524f3b82d'
down_revision = 'a06d8a8ba2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contacto', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=200), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DATETIME(), nullable=True),
    sa.Column('notas', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
