"""descripción del cambio

Revision ID: bfaa769d66e3
Revises: e47ca18d5f3f
Create Date: 2025-05-17 19:25:24.860148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfaa769d66e3'
down_revision = 'e47ca18d5f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_repuesto_codigo', ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.drop_constraint('uq_repuesto_codigo', type_='unique')

    # ### end Alembic commands ###
