"""Inicial

Revision ID: e47ca18d5f3f
Revises: 
Create Date: 2025-05-17 19:24:11.616848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47ca18d5f3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultima_visita', sa.DateTime(), nullable=True),
    sa.Column('preferencias', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('subtitulo', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('fondo', sa.String(length=200), nullable=True),
    sa.Column('colores', sa.JSON(), nullable=True),
    sa.Column('etiquetas', sa.JSON(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_licencia', sa.String(length=64), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('max_usuarios', sa.Integer(), nullable=True),
    sa.Column('hash_verificacion', sa.String(length=64), nullable=False),
    sa.Column('archivo_licencia', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_licencia')
    )
    op.create_table('mecanico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('tarifa_hora', sa.Float(), nullable=True),
    sa.Column('fecha_contratacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('codigo', name='uq_repuesto_codigo')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('licencia_id', sa.Integer(), nullable=True),
    sa.Column('clave_activacion', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['licencia_id'], ['licencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave_activacion'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('kilometraje', sa.Float(), nullable=True),
    sa.Column('ultimo_servicio', sa.DateTime(), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('tipo_combustible', sa.String(length=20), nullable=True),
    sa.Column('transmision', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('fecha_estimada_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('prioridad', sa.String(length=10), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('costo_real', sa.Float(), nullable=True),
    sa.Column('honorarios', sa.Float(), nullable=False),
    sa.Column('kilometraje_entrada', sa.Float(), nullable=True),
    sa.Column('kilometraje_salida', sa.Float(), nullable=True),
    sa.Column('nivel_combustible_entrada', sa.Float(), nullable=True),
    sa.Column('nivel_combustible_salida', sa.Float(), nullable=True),
    sa.Column('fecha_aprobacion_cliente', sa.DateTime(), nullable=True),
    sa.Column('motivo_cancelacion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivo_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=50), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('recordatorio', sa.Boolean(), nullable=True),
    sa.Column('recordatorio_enviado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanico.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('impuestos', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('foto_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ruta_foto', sa.String(length=500), nullable=False),
    sa.Column('fecha_toma', sa.DateTime(), nullable=True),
    sa.Column('es_camara', sa.Boolean(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo_mantenimiento', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('kilometraje', sa.Float(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hora_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horas_trabajadas', sa.Float(), nullable=False),
    sa.Column('tipo_trabajo', sa.String(length=50), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanico.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicio_repuesto',
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('servicio_id', 'repuesto_id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('enviada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('notificacion')
    op.drop_table('servicio_repuesto')
    op.drop_table('movimiento_inventario')
    op.drop_table('hora_trabajo')
    op.drop_table('historial_mantenimiento')
    op.drop_table('historial_estados')
    op.drop_table('foto_servicio')
    op.drop_table('factura')
    op.drop_table('evento')
    op.drop_table('archivo_servicio')
    op.drop_table('servicio')
    op.drop_table('vehiculo')
    op.drop_table('usuario')
    op.drop_table('repuesto')
    op.drop_table('mecanico')
    op.drop_table('licencia')
    op.drop_table('configuracion')
    op.drop_table('cliente')
    # ### end Alembic commands ###
